# -*- coding: utf-8 -*-
"""ADS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wgatu1kYeY7ZX2CC9cVNvxBNk9nWQc-5
"""
import json
import os

class Heap:
    def __init__(self):
        self.heap = []

    def heap_size(self):
        return len(self.heap)

    def swap(self, i, j):
        temp = self.heap[i]
        self.heap[i] = self.heap[j]
        self.heap[j] = temp

    def insert(self, item):
        self.heap.append(item)
        self.fix_up(self.heap_size() - 1)

    def fix_up(self, index):
        parent_index = (index - 1) // 2
        if index > 0 and self.heap[index][0] > self.heap[parent_index][0]:
            self.swap(index, parent_index)
            self.fix_up(parent_index)

    def get_max(self):
        if self.heap_size() == 0:
            return None
        return self.heap[0]

    def pop_max(self):
        if self.heap_size() == 0:
            return None

        max_item = self.heap[0]
        last_index = self.heap_size() - 1
        self.swap(0, last_index)
        self.heap.pop()

        if self.heap_size() > 0:
            self.fix_down(0)

        return max_item

    def fix_down(self, index):
        left = 2 * index + 1
        right = 2 * index + 2
        largest = index

        if left < self.heap_size() and self.heap[left][0] > self.heap[largest][0]:
            largest = left

        if right < self.heap_size() and self.heap[right][0] > self.heap[largest][0]:
            largest = right

        if largest != index:
            self.swap(index, largest)
            self.fix_down(largest)

def create_user(users):
    print("\nLet's create your StudyLink profile!")

    # email check
    email = input("Enter your IE email (@student.ie.edu): ").strip().lower()
    while "@student.ie.edu" not in email:
        print("Invalid email. Please use your official IE email.")
        email = input("Enter your IE email (@student.ie.edu): ").strip().lower()

    # username
    username = input("Enter your username: ").strip().lower()
    while username in users:
        print("This username already exists, choose another one.")
        username = input("Enter your username: ").strip().lower()

    # degree
    degree = input("Enter your degree (e.g. BBA, BBABDA, LLB): ").strip().lower()

    # campus
    campus = input("Enter your campus (Madrid/Segovia): ").strip().lower()
    while campus not in ["madrid", "segovia"]:
        print("Invalid campus.")
        campus = input("Enter your campus (Madrid/Segovia): ").strip().lower()

    # classes
    classes = input("Enter your classes separated by commas: ").strip().lower()
    class_set = set(c.strip() for c in classes.split(","))

    # availability
    availability = input("Enter your availability (e.g. mon-10, wed-16) separated by commas: ").strip().lower()
    avail_set = set(a.strip() for a in availability.split(","))

    # preferences
    preferences = input("Enter your study preferences (e.g. quiet, discussion, willing_to_tutor): ").strip().lower()
    pref_set = set(p.strip() for p in preferences.split(","))

    # save to dictionary
    users[username] = [
        email,
        degree,
        campus,
        class_set,
        avail_set,
        pref_set
    ]

    save_users(users)   # save immediately

    print("\nProfile created successfully!\n")

def compute_score(users, user1, user2):
    data1 = users[user1]
    data2 = users[user2]

    # unpack 6-element structure
    email1, degree1, campus1, classes1, avail1, prefs1 = data1
    email2, degree2, campus2, classes2, avail2, prefs2 = data2

    shared_classes = len(classes1 & classes2)
    shared_slots = len(avail1 & avail2)
    shared_prefs = len(prefs1 & prefs2)

    score = 0
    score += 5 * shared_classes
    score += 3 * shared_slots
    if campus1 == campus2:
        score += 4
    score += 2 * shared_prefs

    return score

def build_matches_heap(users, current_user):
    heap = Heap()

    for other_user in users:
        if other_user == current_user:
            continue

        score = compute_score(users, current_user, other_user)
        if score > 0:
            heap.insert((score, other_user))

    return heap

def show_best_matches(users):
    print("\nAvailable users in the system:")
    for name in users.keys():
        print("-", name)

    current_user = input("\nEnter your username to see your best study matches: ").strip().lower()
    while current_user not in users:
        print("This username does not exist, please try again.")
        current_user = input("Enter your username: ").strip().lower()

    heap = build_matches_heap(users, current_user)

    if heap.heap_size() == 0:
        print("\nNo compatible matches found yet.\n")
        return

    print("\nThese are your best study matches:\n")
    k = 3
    count = 0

    while count < k and heap.heap_size() > 0:
        score, name = heap.pop_max()
        email = users[name][0]                # get matched user's email
        print("Match:", name, "- score:", score)
        print("Contact them at:", email)
        print()
        count += 1
    print()


def load_users():
    path = "resources/users.json"
    if not os.path.exists(path):
        return {}

    with open(path, "r") as f:
        raw = json.load(f)

    users = {}
    for username, data in raw.items():
        email, degree, campus, classes, avail, prefs = data
        users[username] = [
            email,
            degree,
            campus,
            set(classes),
            set(avail),
            set(prefs)
        ]
    return users


def save_users(users):
    path = "resources/users.json"
    raw = {}

    for username, data in users.items():
        email, degree, campus, classes, avail, prefs = data
        raw[username] = [
            email,
            degree,
            campus,
            list(classes),
            list(avail),
            list(prefs)
        ]

    with open(path, "w") as f:
        json.dump(raw, f, indent=2)

def main():
    users = load_users()

    while True:
        print("1) Create user")
        print("2) Show matches")
        print("3) Quit")
        choice = input("Choose an option: ").strip()

        if choice == "1":
            create_user(users)
        elif choice == "2":
            if len(users) == 0:
                print("No users in the system yet.")
            else:
                show_best_matches(users)
        elif choice == "3":
            print("Goodbye!")
            break
        else:
            print("Invalid option, try again.")


main()

